"""
off_policy_train.py

This script loads the evolutionary dataset generated by generate_dataset.py,
populates a replay buffer with the transitions, performs off-policy training
using the DDPG algorithm, logs training metrics, and then performs full evaluation
episodes periodically. At every 5% of training, all plots (losses, reward progression,
aggregated histograms, and a detailed evaluation episode figure) and the model checkpoint 
are saved to a separate checkpoint directory.
"""

import os
import yaml
import torch
import random
import argparse
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import numpy as np
from tqdm import trange, tqdm
import time

try:
    import wandb
except ImportError:  # pragma: no cover - wandb may not be installed in tests
    wandb = None


from rl_agent import DDPGAgent
from replay_buffer import build_augmented_replay_buffer
from curriculum_env import CurriculumEnv
from utils import select_top_percent, behavior_clone, tune_value_function

def set_seed(seed: int):
    """Set random seeds for reproducibility."""
    random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

def load_config(config_file):
    with open(config_file, 'r') as f:
        config = yaml.safe_load(f)
    return config

# ----- Episode Plotting Functions (adapted from analyze_history.py) -----

def breakdown_state(state, num_bins):
    """
    Breaks down the state vector into its constituent parts.
    Assumes the following layout:
      - Indices 0:num_bins                  : Easy Correct Histogram
      - Indices num_bins:2*num_bins         : Easy Incorrect Histogram
      - Indices 2*num_bins:3*num_bins       : Medium Correct Histogram
      - Indices 3*num_bins:4*num_bins       : Medium Incorrect Histogram
      - Indices 4*num_bins:5*num_bins       : Hard Correct Histogram
      - Indices 5*num_bins:6*num_bins       : Hard Incorrect Histogram
      - Indices 6*num_bins:6*num_bins+3     : Relative dataset sizes (3 values)
      - Indices 6*num_bins+3:6*num_bins+5     : Extra state features (2 values)
    Total length = 6*num_bins + 5.
    """
    if not torch.is_tensor(state):
        state = torch.tensor(state, dtype=torch.float32)
        
    breakdown = {}
    breakdown['easy_correct_hist'] = state[0:num_bins].tolist()
    breakdown['easy_incorrect_hist'] = state[num_bins:2*num_bins].tolist()
    breakdown['medium_correct_hist'] = state[2*num_bins:3*num_bins].tolist()
    breakdown['medium_incorrect_hist'] = state[3*num_bins:4*num_bins].tolist()
    breakdown['hard_correct_hist'] = state[4*num_bins:5*num_bins].tolist()
    breakdown['hard_incorrect_hist'] = state[5*num_bins:6*num_bins].tolist()
    breakdown['relative_sizes'] = state[6*num_bins:6*num_bins+3].tolist()
    breakdown['extra'] = state[6*num_bins+3:6*num_bins+5].tolist()
    return breakdown

def breakdown_action(action):
    """
    Breaks down the 5-dimensional action vector into:
      - Learning rate: action[0]
      - Mixing ratios for (Easy, Medium, Hard): action[1:4]
      - Sample usage fraction: action[4]
    """
    if not torch.is_tensor(action):
        action = torch.tensor(action, dtype=torch.float32)
        
    breakdown = {}
    breakdown['learning_rate'] = action[0].tolist()
    breakdown['mixing_ratios'] = action[1:4].tolist()
    breakdown['sample_usage_fraction'] = action[4].tolist()
    return breakdown


def plot_episode_figure(episode, group_name, num_bins, output_dir):
    """Create a detailed episode figure matching analyze_history.py styling."""
    # Bin edges taken from analyze_history.py
    min_val, max_val, alpha = 0.0, 13.8, 2.0
    rel = torch.linspace(0, 1, num_bins + 1)
    edges = (min_val + (max_val - min_val) * (rel ** alpha)).tolist()
    centers = [(edges[i] + edges[i+1]) / 2 for i in range(len(edges)-1)]
    widths = [edges[i+1] - edges[i] for i in range(len(edges)-1)]

    states = episode["states"]
    actions = episode["actions"]
    rewards = episode["rewards"]
    num_phases = len(states)

    fig = plt.figure(figsize=(20, num_phases * 3 + 3))
    fig.patch.set_facecolor("#fffaf0")
    fig.suptitle("\U0001F389 Fun Episode Analysis \U0001F389", fontsize=18, fontweight="bold", y=0.995)

    gs_top = gridspec.GridSpec(nrows=num_phases, ncols=4, top=0.90, bottom=0.55,
                               wspace=0.4, hspace=0.6, height_ratios=[1]*num_phases)
    gs_bot = gridspec.GridSpec(nrows=1, ncols=4, top=0.50, bottom=0.05, wspace=0.5)

    for i in range(num_phases):
        s = states[i]
        r = rewards[i]
        sb = breakdown_state(s, num_bins)

        ax0 = fig.add_subplot(gs_top[i, 0])
        ax0.set_facecolor("#f5f5f5")
        ax0.bar(centers, sb["easy_correct_hist"], widths, align="center", color="green", hatch="//", alpha=0.7, label="Correct")
        ax0.bar(centers, sb["easy_incorrect_hist"], widths, align="center", color="red", hatch="xx", alpha=0.7, label="Incorrect")
        if i == 0:
            ax0.set_title("Easy Loss Hist", fontsize=10, fontweight="bold")
            ax0.legend(fontsize=8)
        ax0.set_ylabel(f"P{i+1}\nR:{r:.2f}", fontsize=9)
        ax0.grid(True, linestyle="--", alpha=0.5)
        ax0.tick_params(axis="both", labelsize=8, rotation=45)
        ax0.set_xticks(edges)

        ax1 = fig.add_subplot(gs_top[i, 1])
        ax1.set_facecolor("#f5f5f5")
        ax1.bar(centers, sb["medium_correct_hist"], widths, color="green", hatch="//", alpha=0.7)
        ax1.bar(centers, sb["medium_incorrect_hist"], widths, color="red", hatch="xx", alpha=0.7)
        if i == 0:
            ax1.set_title("Medium Loss Hist", fontsize=10, fontweight="bold")
        ax1.grid(True, linestyle="--", alpha=0.5)
        ax1.tick_params(axis="both", labelsize=8, rotation=45)
        ax1.set_xticks(edges)

        ax2 = fig.add_subplot(gs_top[i, 2])
        ax2.set_facecolor("#f5f5f5")
        ax2.bar(centers, sb["hard_correct_hist"], widths, color="green", hatch="//", alpha=0.7)
        ax2.bar(centers, sb["hard_incorrect_hist"], widths, color="red", hatch="xx", alpha=0.7)
        if i == 0:
            ax2.set_title("Hard Loss Hist", fontsize=10, fontweight="bold")
        ax2.grid(True, linestyle="--", alpha=0.5)
        ax2.tick_params(axis="both", labelsize=8, rotation=45)
        ax2.set_xticks(edges)

        ax3 = fig.add_subplot(gs_top[i, 3])
        ax3.set_facecolor("#f5f5f5")
        info = sb["relative_sizes"] + sb["extra"]
        ax3.bar(range(5), info, color=["blue", "orange", "purple", "cyan", "magenta"], alpha=0.8)
        if i == 0:
            ax3.set_title("State Info", fontsize=10, fontweight="bold")
        ax3.set_xticks(range(5))
        ax3.set_xticklabels(["Easy", "Med", "Hard", "PhaseRatio", "AvailRatio"], rotation=45, fontsize=8)
        ax3.tick_params(axis="both", labelsize=8)
        ax3.grid(True, linestyle="--", alpha=0.5)
        ax3.text(2, max(info)*1.05, f"R={r:.1f}", ha="center", fontsize=8, color="darkred")

    phases = list(range(1, num_phases + 1))
    lrs, usage, mixrs = [], [], []
    for a in actions:
        if torch.is_tensor(a):
            a = a.detach().cpu()
        lrs.append(float(a[0]))
        usage.append(float(a[4]))
        mixrs.append([float(x) for x in a[1:4]])
    rews = [float(r) for r in rewards]
    if rews:
        rews[-1] = rews[-1] / 10.0

    ax_lr = fig.add_subplot(gs_bot[0, 0])
    ax_lr.set_facecolor("#f5f5f5")
    ax_lr.plot(phases, lrs, marker="D", linestyle="-", color="blue", markersize=6)
    ax_lr.set_title("Learning Rate")
    ax_lr.set_xlabel("Phase")
    ax_lr.set_ylabel("LR")
    ax_lr.set_xticks(phases)
    ax_lr.grid(True, linestyle=":", alpha=0.6)

    ax_us = fig.add_subplot(gs_bot[0, 1])
    ax_us.set_facecolor("#f5f5f5")
    ax_us.plot(phases, usage, marker="D", linestyle="-", color="orange", markersize=6)
    ax_us.set_title("Sample Usage")
    ax_us.set_xlabel("Phase")
    ax_us.set_ylabel("Usage")
    ax_us.set_xticks(phases)
    ax_us.grid(True, linestyle=":", alpha=0.6)

    ax_mx = fig.add_subplot(gs_bot[0, 2])
    ax_mx.set_facecolor("#f5f5f5")
    bar_w = 0.6
    for idx, mr in enumerate(mixrs):
        bottom = 0.0
        ax_mx.bar(idx, mr[0], bottom=bottom, width=bar_w, color="green", label="Easy" if idx == 0 else "")
        bottom += mr[0]
        ax_mx.bar(idx, mr[1], bottom=bottom, width=bar_w, color="yellow", label="Med" if idx == 0 else "")
        bottom += mr[1]
        ax_mx.bar(idx, mr[2], bottom=bottom, width=bar_w, color="red", label="Hard" if idx == 0 else "")
    ax_mx.set_xticks(range(num_phases))
    ax_mx.set_xticklabels([f"P{p}" for p in phases])
    ax_mx.set_title("Mixing Ratios")
    ax_mx.set_xlabel("Phase")
    ax_mx.set_ylabel("Ratio")
    ax_mx.legend(fontsize=8)
    ax_mx.grid(True, linestyle=":", alpha=0.6)

    ax_rw = fig.add_subplot(gs_bot[0, 3])
    ax_rw.set_facecolor("#f5f5f5")
    ax_rw.plot(phases, rews, marker="D", linestyle="-", color="magenta", markersize=6)
    ax_rw.set_title("Reward")
    ax_rw.set_xlabel("Phase")
    ax_rw.set_ylabel("Reward")
    ax_rw.set_xticks(phases)
    ax_rw.grid(True, linestyle=":", alpha=0.6)

    fig.subplots_adjust(top=0.90, bottom=0.05, left=0.05, right=0.98, hspace=0.6, wspace=0.4)
    fname = os.path.join(output_dir, f"{group_name}_episode_{episode['index']}_detailed.png")
    plt.savefig(fname)
    plt.close(fig)
    print(f"Saved detailed figure for {group_name} episode {episode['index']} to {fname}")
# ----- Main Training and Evaluation -----

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--config", "-c",
        default="config.yaml",
        help="path to your config YAML"
    )
    args   = parser.parse_args()
    config = load_config(args.config)

    # config = load_config("config.yaml")
    set_seed(42)

    # Create a separate directory for checkpoints/plots.
    results_dir = os.path.join("results", "off_policy")
    os.makedirs(results_dir, exist_ok=True)

    # Setup Weights & Biases logging if available
    if wandb is not None:
        wandb.init(project="off_policy_training", config=config)
    else:  # pragma: no cover - warn if wandb missing
        print("wandb not installed; proceeding without online logging")

    # Paths for hourly checkpoint overwriting
    hourly_actor = os.path.join(results_dir, "off_policy_actor_latest.pth")
    hourly_critic1 = os.path.join(results_dir, "off_policy_critic1_latest.pth")
    hourly_critic2 = os.path.join(results_dir, "off_policy_critic2_latest.pth")
    last_hour_save = time.time()
    
    # Load dataset (must be a .pt saved via torch.save)
    dataset_path = config["paths"]["pretrain_path"]
    data = torch.load(dataset_path, map_location="cpu")
    states      = data["states"]
    actions     = data["actions"]
    rewards     = data["rewards"]
    next_states = data["next_states"]
    dones       = data["dones"]
    dataset = {
        "states": states,
        "actions": actions,
        "rewards": rewards,
        "next_states": next_states,
        "dones": dones,
    }
    print(f"Loaded dataset from {dataset_path} with {len(states)} transitions")

    env = CurriculumEnv(config)
    obs_dim = len(env.reset())
    action_dim = 5
    agent = DDPGAgent(obs_dim, action_dim, config)

    elite_fraction = config["rl"].get("elite_fraction", 0.1)
    top_percent = elite_fraction * 100
    elite_data = select_top_percent(dataset, top_percent)
    replay_buffer = build_augmented_replay_buffer(
        elite_data,
        dataset,
        config["rl"]["buffer_size"],
        elite_fraction,
        config["device"],
        use_per=config["rl"].get("per_enabled", False),
        per_alpha=config["rl"].get("per_alpha", 0.4),
        per_beta=config["rl"].get("per_beta", 0.6),
        per_epsilon=config["rl"].get("per_epsilon", 1e-6),
        per_type=config["rl"].get("per_type", "proportional"),
    )
    print(
        f"Replay buffer initialized with {len(replay_buffer)} transitions "
        f"(capacity {config['rl']['buffer_size']})"
    )

    probe_batch_size = 256
    perm = torch.randperm(len(states))
    idxs = perm[:probe_batch_size]
    variance_states_tensor = states[idxs].to(agent.device).float()

    # Prepare for training and evaluation intervals.
    num_updates = config["rl"].get("off_policy_updates", int(1e6))
    evaluation_interval = max(1, num_updates // 100)  # 100 evaluations total
    checkpoint_interval = max(1, num_updates // 20)   # save model every 5%
    print(f"Starting off-policy training for {num_updates} updates")

    # Lists for tracking metrics over training.
    actor_losses = []
    critic1_losses = []
    critic2_losses = []
    reward_progress = []
    reward_stds = []
    eval_updates = []
    num_bins = config["observation"]["num_bins"]
    action_var_history = []
    update_steps      = []

    best_mean_reward = -float("inf")
    no_improve = 0
    early_stop = config["rl"].get("early_stop_patience")

    # Training loop.
    last_actor_loss = 0.0
    num_eval_eps = config["rl"].get("num_eval_episodes", 1)
    stop_training = False
    for update in trange(num_updates, desc="Off‑policy Training"):
        if len(replay_buffer) >= config["rl"]["batch_size"]:
            metrics = agent.update(replay_buffer, config["rl"]["batch_size"])
            if metrics is not None:
                if metrics["actor_loss"] is not None:
                    last_actor_loss = metrics["actor_loss"]
                actor_losses.append(last_actor_loss)
                critic1_losses.append(metrics["critic1_loss"])
                critic2_losses.append(metrics["critic2_loss"])
                if wandb is not None:
                    wandb.log({
                        "actor_loss": last_actor_loss,
                        "critic1_loss": metrics["critic1_loss"],
                        "critic2_loss": metrics["critic2_loss"],
                        "update": update,
                    })
        with torch.no_grad():
            pred_actions = agent.actor(variance_states_tensor).cpu() # (256,5)
        var = torch.var(pred_actions, dim=0, unbiased=False)  # length‑5 vector
        action_var_history.append(var.tolist())
        update_steps.append(update)

        # Hourly checkpoint save
        if time.time() - last_hour_save >= 3600:
            torch.save(agent.actor.state_dict(), hourly_actor)
            torch.save(agent.critic1.state_dict(), hourly_critic1)
            torch.save(agent.critic2.state_dict(), hourly_critic2)
            print(f"Hourly checkpoint saved at update {update}")
            last_hour_save = time.time()
        
        # Periodically evaluate the policy without saving a model checkpoint.
        if update % evaluation_interval == 0:
            rewards_this_ckpt = []
            first_episode = None
            for ep_i in range(num_eval_eps):
                eval_states = []
                eval_actions = []
                eval_rewards = []
                obs_eval = env.reset()
                done = False
                with tqdm(total=env.max_phases, desc=f"Eval {update} Ep{ep_i}", leave=False) as pbar:
                    while not done:
                        action_eval = agent.select_action(obs_eval, noise_enable=False)
                        eval_states.append(obs_eval)
                        eval_actions.append(action_eval)
                        obs_eval, reward, done = env.step(action_eval)
                        eval_rewards.append(reward)
                        pbar.update(1)
                total_reward = sum(eval_rewards)
                rewards_this_ckpt.append(total_reward)
                if ep_i == 0:
                    first_episode = {
                        "index": update,
                        "states": eval_states,
                        "actions": eval_actions,
                        "rewards": eval_rewards,
                        "total_reward": total_reward,
                        "episode_length": len(eval_states),
                    }
            mean_reward = float(np.mean(rewards_this_ckpt))
            std_reward = float(np.std(rewards_this_ckpt))
            reward_progress.append(mean_reward)
            reward_stds.append(std_reward)
            eval_updates.append(update)
            print(f"Checkpoint at update {update}/{num_updates} - Eval reward {mean_reward:.2f} ± {std_reward:.2f}")
            if wandb is not None:
                wandb.log({
                    "eval_mean_reward": mean_reward,
                    "eval_std_reward": std_reward,
                    "update": update,
                })

            eval_episode = first_episode

            if mean_reward > best_mean_reward:
                best_mean_reward = mean_reward
                torch.save(agent.actor.state_dict(), os.path.join(results_dir, "best_actor.pth"))
                torch.save(agent.critic1.state_dict(), os.path.join(results_dir, "best_critic1.pth"))
                torch.save(agent.critic2.state_dict(), os.path.join(results_dir, "best_critic2.pth"))
                no_improve = 0
            else:
                no_improve += 1

            if early_stop is not None and no_improve >= early_stop:
                print(f"Early stopping at update {update} due to no improvement")
                stop_training = True
                break
            
            # Save detailed episode plot.
            plot_episode_figure(eval_episode, f"eval_{update}", num_bins, results_dir)
            
            # Save loss plots.
            fig_loss, (ax_actor, ax_critic) = plt.subplots(2, 1, figsize=(8, 10))
            ax_actor.plot(actor_losses, color='blue')
            ax_actor.set_title("Actor Loss Progression")
            ax_actor.set_xlabel("Update Steps")
            ax_actor.set_ylabel("Loss")
            ax_critic.plot(critic1_losses, label="Critic1")
            ax_critic.plot(critic2_losses, label="Critic2")
            ax_critic.set_title("Critic Loss Progression")
            ax_critic.set_xlabel("Update Steps")
            ax_critic.set_ylabel("Loss")
            ax_critic.legend()
            checkpoint_loss_path = os.path.join(results_dir, f"training_losses_{update}.png")
            fig_loss.tight_layout()
            fig_loss.savefig(checkpoint_loss_path)
            plt.close(fig_loss)
            
            # Save reward progression plot.
            plt.figure()
            plt.errorbar(eval_updates, reward_progress, yerr=reward_stds, marker='o', capsize=3)
            plt.xlabel("Update Steps")
            plt.ylabel("Reward")
            plt.title("Periodic Reward Evaluation")
            checkpoint_reward_path = os.path.join(results_dir, f"reward_progress_{update}.png")
            plt.savefig(checkpoint_reward_path)
            plt.close()
            
            # Save model checkpoint every checkpoint_interval
            if update % checkpoint_interval == 0:
                actor_ckpt = os.path.join(results_dir, f"off_policy_actor_{update}.pth")
                torch.save(agent.actor.state_dict(), actor_ckpt)
                crit1_ckpt = os.path.join(results_dir, f"off_policy_critic1_{update}.pth")
                crit2_ckpt = os.path.join(results_dir, f"off_policy_critic2_{update}.pth")
                torch.save(agent.critic1.state_dict(), crit1_ckpt)
                torch.save(agent.critic2.state_dict(), crit2_ckpt)
                print(f"Saved actor → {actor_ckpt}")
                print(f"Saved critic1 → {crit1_ckpt}")
                print(f"Saved critic2 → {crit2_ckpt}")

            # plot action‐component variances
            action_var_array = torch.tensor(action_var_history)  # shape (steps,5)
            names = ["learning_rate","mix_easy","mix_med","mix_hard","sample_usage"]

            # 5‐panel subplot, one row per action component
            fig, axs = plt.subplots(nrows=5, ncols=1, figsize=(8,12), sharex=True)
            for idx, name in enumerate(names):
                axs[idx].plot(update_steps, action_var_array[:,idx].numpy())
                axs[idx].set_ylabel("Var")
                axs[idx].set_title(name)
                axs[idx].grid(True)

            # only bottom panel needs an x‐label
            axs[-1].set_xlabel("Update Step")

            plt.tight_layout()
            plt.savefig(os.path.join(results_dir, "action_variance.png"))
            plt.close()

        if stop_training:
            break
                
    # After training, run one final full evaluation episode.
    eval_states = []
    eval_actions = []
    eval_rewards = []
    obs_eval = env.reset()
    done = False
    with tqdm(total=env.max_phases, desc="Final Eval", leave=False) as pbar:
        while not done:
            action_eval = agent.select_action(obs_eval, noise_enable=False)
            eval_states.append(obs_eval)
            eval_actions.append(action_eval)
            obs_eval, reward, done = env.step(action_eval)
            eval_rewards.append(reward)
            pbar.update(1)
    total_reward = sum(eval_rewards)
    print(f"Final evaluation episode total reward: {total_reward}")
    
    final_index = update if stop_training else num_updates
    eval_episode = {
        "index": final_index,
        "states": eval_states,
        "actions": eval_actions,
        "rewards": eval_rewards,
        "total_reward": total_reward,
        "episode_length": len(eval_states)
    }
    plot_episode_figure(eval_episode, "final_eval", num_bins, results_dir)
    print(f"Saved final evaluation episode plot in {results_dir}")
    
    # Final actor save
    final_actor = os.path.join(results_dir, "off_policy_actor_model_final.pth")
    torch.save(agent.actor.state_dict(), final_actor)

    final_critic1 = os.path.join(results_dir, "off_policy_critic1_model_final.pth")
    final_critic2 = os.path.join(results_dir, "off_policy_critic2_model_final.pth")

    torch.save(agent.critic1.state_dict(), final_critic1)
    torch.save(agent.critic2.state_dict(), final_critic2)

    print(f"Saved final actor → {final_actor}")
    print(f"Saved final critic 1 → {final_critic1}")
    print(f"Saved final critic 2 → {final_critic2}")
    
    # Plot final actor and critic loss progression on separate subplots.
    fig_loss, (ax_actor, ax_critic) = plt.subplots(2, 1, figsize=(8, 10))
    ax_actor.plot(actor_losses, color='blue')
    ax_actor.set_title("Actor Loss Progression")
    ax_actor.set_xlabel("Update Steps")
    ax_actor.set_ylabel("Loss")
    ax_critic.plot(critic1_losses, color='red', label="Critic 1")
    ax_critic.plot(critic2_losses, color='green', label="Critic 2")
    ax_critic.set_title("Critic Loss Progression")
    ax_critic.set_xlabel("Update Steps")
    ax_critic.set_ylabel("Loss")
    ax_critic.legend()
    final_loss_plot = os.path.join(results_dir, "training_losses_final.png")
    fig_loss.tight_layout()
    fig_loss.savefig(final_loss_plot)
    plt.close(fig_loss)
    print(f"Final training loss plot saved to {final_loss_plot}")
    
    # Plot final reward progression.
    plt.figure()
    plt.errorbar(eval_updates, reward_progress, yerr=reward_stds, marker='o', capsize=3)
    plt.xlabel("Update Steps")
    plt.ylabel("Reward")
    plt.title("Periodic Reward Evaluation")
    final_reward_plot = os.path.join(results_dir, "reward_progress_final.png")
    plt.savefig(final_reward_plot)
    plt.close()
    print(f"Final reward progression plot saved to {final_reward_plot}")

    if wandb is not None:
        wandb.log({"final_total_reward": total_reward})
        wandb.finish()

if __name__ == "__main__":
    main()





